# Global settings applied to the whole site.
[build]
  command = "yarn run build"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "8.10.0"